### ISSUE TITLE
PrepareItemCraftEvent receives a null ItemStack

### ISSUE THREAD

**Issue by luizsusin** [Auxilor/eco#102]
**Describe the bug**
Players can't craft default items, only EcoItems/EcoArmor items.

**To Reproduce**
1. Try to craft a Vanilla item (tested with golden pickaxe and a few others)
2. You can't, and it returns the error in the gist.

**Expected behavior**
Players should be able to craft EcoItems/EcoArmor items and vanilla items as well.
This has started happening in the 6.26.0 version.

**Server Information (please complete the following information):**
- Version: git-Purpur-1564 (MC: 1.18.1)
- Version of plugin and eco: eco version 6.26.1

**Additional context**
Error on the log file: https://gist.github.com/luizsusin/0bdeba05e42bee6c83d7df3a4359b516

**Comment by WillFP** [comment]
Fixed
