### ISSUE TITLE
Updated/Fixed KingdomsX integration - Doesnt work

### ISSUE THREAD

**Issue by Aides123** [Auxilor/eco#104]
Describe the bug
After uploading talismans, a bunch of errors appear in the console.
Talismans have only been uploaded and no player has them yet.
Server: 1.18.1 pufferfish
Kingdoms ver: Kingdom: 1.12.2.0.0.1-BETA
https://www.spigotmc.org/resources/kingdomsx.77670/

To Reproduce
Just upload talismans to the server with kingdoms plugin
https://pastebin.com/YWTgZDvF

![image](https://user-images.githubusercontent.com/23367220/156778580-20f4cba5-2423-49e1-bee8-8fe31177b08e.png)

**Comment by WillFP** [comment]
Update kingdoms to 1.12.4
