### ISSUE TITLE
Creating too many recipes prevents you from logging in

### ISSUE THREAD

**Issue by Sedri05** [Auxilor/eco#112]
**Describe the bug**
When creating alot of recipes you will no longer be able to log in getting an error message (see image)

**Screenshots**
![image](https://user-images.githubusercontent.com/88105532/157751280-70ce1551-515b-4263-8fae-7c94dabca72e.png)

**Comment by PrimalPower** [comment]
I have this too. The problem isn't too many recipes. It is too much lore in the recipes. It is inconvenient but I got around it by making any high lore recipe a boss egg in ecobosses and making the recipe the same and the item intended to be crafted a 100% drop from the boss. The boss egg can have less lore so it will use up less packet size. I just write in the boss egg lore that it drops 'this item'.
