### ISSUE TITLE
New API MythicMobs send error

### ISSUE THREAD

**Issue by EneRGO22** [Auxilor/eco#113]
https://pastebin.com/jsF34P2n

![image](https://user-images.githubusercontent.com/68811273/157948386-a30b3934-9daa-4834-932d-99ab3ce04c4c.png)
![image](https://user-images.githubusercontent.com/68811273/157948411-397ab27c-16c9-44d4-a5e7-549d03a1a31a.png)

**Comment by GazpaNova** [comment]
Just wanted to add here, this also means the other eco plugins have to be updated to use the new api too. EcoEnchants throws some funny errors here and there

https://pastebin.pl/view/725c04a0
