### ISSUE TITLE
Eco and EcoCrates don’t works with the plugin UltimateShoutPro after update

### ISSUE THREAD

**Issue by Jeroen123TC** [Auxilor/eco#121]
**Describe the bug**
Since i updated eco/ EcoEnchants and EcoCrates to the latest version, EcoCrates will not work any more, i have discuss it in the support discord. They sad that the plugin UltimaShoutPro need to update to te latest kotlin version but it is already the latest. 

Its kind of weird, EcoEnchants works fine. 

**To Reproduce**
….

**Expected behavior**
The Eco plugins just need to work normaly together with the other plugins like UltimateShoudPro

**Screenshots**
https://pastebin.com/0tfNkKzN

**Server Information (please complete the following information):**
- Version: paper 1.18.2
- Version of plugins Eco: 6.30.0/EcoEnchants: 8.51.0/UltimateShoutPro1.1.0

**Additional context**

**Comment by WillFP** [comment]
I can modify UltimateShoutPro to make it work if you want - the dev needs to shade **and relocate** kotlin
