### ISSUE TITLE
Creating too many recipes causes PacketTooLarge internal exception

### ISSUE THREAD

**Issue by luizsusin** [Auxilor/eco#140]
**Describe the bug**
Creating too many recipes causes PacketTooLarge Internal Exception to be thrown.

**To Reproduce**
Create a lot of recipes (not really sure how many) and this will be thrown on player join.

**Expected behavior**
Players shouldn't receive the recipes all at once. This might be happening on a single packet too.

**Server Information (please complete the following information):**
- Server version: git-Purpur-1615
- Version of eco: 6.35.3

**Additional context**
The exception that is thrown:
`[Server thread/INFO]: PLAYER lost connection: Internal Exception: net.minecraft.network.PacketEncoder$PacketTooLargeException: PacketTooLarge - PacketPlayOutRecipeUpdate is 3519210. Max is 2097152`

**Comment by Booquefius** [comment]
Can reproduce 👍🏻

**Comment by WillFP** [comment]
Yep - known bug, will fix

**Comment by WillFP** [comment]
I've worked on this bug for a while and I haven't been able to fix it yet - I've got the packet splitting working fine, all the packets are being sent, but the client then isn't getting all the recipes to show up - I don't actually know if this is a solvable issue.

**Comment by WillFP** [comment]
<img width="730" alt="Screenshot 2022-05-28 at 13 58 17" src="https://user-images.githubusercontent.com/38837418/170826572-ae5038a8-f842-40b9-9661-3eca8d7412bf.png">

Not really a fix, but it will have to do - set this to false to 'fix' the problem. Coming in eco 6.36.0
