### ISSUE TITLE
Not relocating Caffeine breaks Libertybans

### ISSUE THREAD

**Issue by AlessioGr** [Auxilor/eco#149]
**Describe the bug**
![image](https://user-images.githubusercontent.com/70709113/170873585-8b8461a8-fe70-4efd-92ad-2c2346cde2be.png)

**Comment by WillFP** [comment]
You could also just tell libertybans to relocate it? I can't relocate it in eco because then i'd have to do the same in every other eco plugin - and that's just a janky way of doing things

**Comment by DaRacci** [comment]
> You could also just tell libertybans to relocate it? I can't relocate it in eco because then i'd have to do the same in every other eco plugin - and that's just a janky way of doing things

This is also now breaking my own plugins due to loading kotlin through the spigot loader, Please think of a better way of doing this, such as just a shadowJar auto relocation that is needed for any projects that rely on them, ex 
```kotlin
    val relocateShadowJar by creating(ConfigureShadowRelocation::class) {
        target = shadowJar.get()
        prefix = "dev.racci.minix.libs"
    }

    shadowJar {
        dependsOn(relocateShadowJar)
        // Fix relocation of minix.
        relocate("dev.racci.minix.libs.dev.racci.minix", "dev.racci.minix")
        dependencyFilter.include {
            it.moduleGroup == "org.bstats" ||
                it.moduleGroup == "io.sentry" ||
                it.moduleName == "Minix-Core" ||
                it.moduleName == "Minix-API"
        }
    }
```
