### ISSUE TITLE
WorldGuard's PVP flag will prevent self_as_victim effects

### ISSUE THREAD

**Issue by luizsusin** [Auxilor/eco#156]
**Describe the bug**
Effects with self_as_victim won't work if WorldGuard's PVP flag is set to false.

**To Reproduce**
1. Create a region;
2. Set PVP flag to false;
3. Effects with "self_as_victim" wont work.

**Expected behavior**
Effects should work even if PVP flag is set to false.

**Server Information:**
- Version: git-Purpur-1628
- Version of eco: 6.37.1

**Comment by WillFP** [comment]
You can add bypass_antigrief_check: true to args
