### ISSUE TITLE
ERROR CONNECTING

### ISSUE THREAD

**Issue by marlon233-omc** [Auxilor/eco#175]
**Describe the bug**
When a user connects to the **ECO** server it generates many error messages.
error: https://www.toptal.com/developers/hastebin/lulocehuka.php

**To Reproduce**
1. Install eco on a 1.19 server
2. Connect to the server and the error will appear.

**Expected behavior**
Eco generates many error messages in the console when connecting to the server 1.19

**Server Information (please complete the following information):**
- Version: git-Paper-81 (MC: 1.19)
- Version of plugin and eco: eco version 6.38.1

**Comment by WillFP** [comment]
Update to 6.38.2
