### ISSUE TITLE
Spigot API messed by DropQueue

### ISSUE THREAD

**Issue by AlexanderMoebius** [Auxilor/eco#187]
**Describe the bug**
If you edit drops from EntityDeathEvent with highest priority the drops are not changed in the drop queue.
By editing the drop queue you don't have information about the origin of the drop.
In my case I want prevent drops of shulker shells from shulkers and wither skulls from wither skeletons. But not the drop from other sources like player kills or destroyed chests.

**Expected behavior**
The Bukkit API should work or the DropQueue should contain more information about drop origin.

**Server Information (please complete the following information):**
- Version: Paper 1.17.1-411, 1.18.2-387 and 1.19.2-132
- Current eco and EcoEnchants

**Comment by WillFP** [comment]
That's due to how events are handled in spigot, just don't use the highest priority - there's nothing I can do about that, unfortunately.
