### ISSUE TITLE
EconomyIntegration: use `BigDecimal` instead of `double`

### ISSUE THREAD

**Issue by lokka30** [Auxilor/eco#202]
In [EconomyIntegration](https://github.com/Auxilor/eco/blob/master/eco-api/src/main/java/com/willfp/eco/core/integrations/economy/EconomyIntegration.java), it is using `double`s instead of `BigDecimal`s (except for the 'exact balance' method). 

This limits the precision of balance operations when dealing with libraries such as [Treasury](https://github.com/lokka30/Treasury) which prefer BigDecimal.

Potential solution: add BigDecimal-type methods to the interface and deprecate the double-type ones; make the double-type calls have a `default` implementation which auto-routes to the BigDecimal-type counterparts.

With this change, among the eventual completion of Treasury v2, I can begin writing the Treasury implementation for eco. 🙂

**Comment by WillFP** [comment]
I'd technically have to make both the `double` and `BigDecimal` implementations default to each other (for backwards compatibility) but this is a great idea, i'll add it!

**Comment by WillFP** [comment]
Coming in 6.43.0!

**Comment by lokka30** [comment]
How are you so fast!? 🤣 
Cheers Aux!
