### ISSUE TITLE
SnakeYaml 1.32/1.33 codePointLimit

### ISSUE THREAD

**Issue by Mirayii** [Auxilor/eco#203]
**Describe the bug**
Newest SnakeYaml on Spigot 1.19.2 (SnakeYaml 1.32) / Paper 1.19.2 (SnakeYaml 1.33) has default size limit set to 3 MB, which affects Eco Data reading from Yaml files.

**To Reproduce**
1. Launch server with Data.yml file size over 3 MB

**Expected behavior**
The plugin will read the file without any issues.

**Server Information (please complete the following information):**
- Version: Paper 1.19.2 Build 179
- eco 6.42.0

**Additional context**
Set LoaderOptions codePointLimit in com.willrp.eco.internal.config.ConfigUtils.kt to 64 MB (64 * 1024 * 1024 as Paper YamlConfiguration default).

**Comment by WillFP** [comment]
Coming in next version!
