### ISSUE TITLE
java.lang.NoClassDefFoundError: me/qKing12/RoyaleEconomy/MultiCurrency/MultiCurrencyHandler

### ISSUE THREAD

**Issue by blockaccion** [Auxilor/eco#297]
**Describe the bug**
The bug is due to the compatibility of the eco plugin with the new RoyaleEconomy plugin

**To Reproduce**
1. Install eco and RoyaleEconomy Legacy Free 1.4.4 (SpigotMC: https://www.spigotmc.org/resources/royaleeconomy-legacy-free.111226/)
2. Run server
3. Check the console

**Server Information**
- Version: Paper version git-Paper-135 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: eff22eb)

- Version of plugin and eco:
eco-6.65.1-all.jar
RoyaleEconomy 1.4.4

**Expected behavior**
The plugins should work correctly and be compatible with each other.

**Additional context**
Server logs:
https://pastebin.com/cm5vuPCC

**Comment by SenPr** [comment]
This happens when RoyaleEconomy doesn't have Multicurrency enabled. It's also painful now that there is a free version and the plugin is closed source.
I will attempt to PR a fix

**Comment by blockaccion** [comment]
The bug is fixed. The author of the RoyaleEconomy plugin (https://www.spigotmc.org/resources/royaleeconomy-legacy-free.111226/) fixed the bug in a new update and it is now compatible with ECO plugins. Download the latest version of the plugin if you have the error.

![image](https://github.com/Auxilor/eco/assets/47571323/be78d930-aa9e-458f-ba1a-c809e2771f90)
