### ISSUE TITLE
Plugin incompatibility: This plugin seems to modify ItemStacks of villager trades

### ISSUE THREAD

**Issue by blablubbabc** [Auxilor/eco#3]
I haven't looked into this too deeply myself, however, a user of one of my plugins ran into the issue that items retrieved from a villager trade (in this case a merchant that has been setup by the plugin "Shopkeepers") did not merge with regular variants of that item.

In this particular case, the user got an (apparantely) regular emerald from a villager trade, and could not merge it with other regular emeralds inside of his inventory. Inspecting the nbt data of these emeralds yielded that the emerald item retrieved from the villager trade contained the additional data `tag: {PublicBukkitValues: {"eco:finalized":1}}`, which causes it to no longer stack with plain emeralds.

According to the reports of that user this issue affects all items retrieved from villager trades.

It seems like this plugin is injecting this data into the items of merchant recipes when it processes outgoing OpenMerchant packets. See:
* https://github.com/Auxilor/eco/blob/master/eco-core/core-plugin/src/main/java/com/willfp/eco/spigot/display/packets/PacketOpenWindowMerchant.java#L31
* https://github.com/Auxilor/eco/blob/master/eco-core/core-nms/v1_16_R3/src/main/java/com/willfp/eco/proxy/v1_16_R3/VillagerTrade.java#L21
* https://github.com/Auxilor/eco/blob/master/eco-util/src/main/java/com/willfp/eco/util/display/Display.java#L138

I haven't looked into the purpose of this, but it apparantely modifies the result item of the trade in a way that is incompatible with non-modified items on the server (i.e. can result in the items to not merge occasionally).
If it is _really_ necessary to modify the ItemStacks sent to clients for display purposes, maybe consider copying the MerchantRecipes before you modify them in the outgoing OpenMerchant packet. _Maybe_ this resolves the issue (untested).

There is another reference to that method that modifies ItemStacks in this way:
* https://github.com/Auxilor/eco/blob/master/eco-core/core-nms/v1_16_R3/src/main/java/com/willfp/eco/proxy/v1_16_R3/ChatComponent.java#L62
But that seems to at least only affect ItemStacks internal of hover events. So as long as no other plugin retrieves the ItemStack from a hover event, this seems to be a comparatively minor risk.

**Comment by Auxilor** [comment]
Fixed in latest version

**Comment by blablubbabc** [comment]
I assume this commit is supposed to fix it? https://github.com/Auxilor/eco/commit/bce1dd9fee85401db8f1e6886d763c6fc377c354

I am not sure how this is supposed to fix it for any items that actually have a max stack size of 1, succh as books, tools, weapons, etc.

**Comment by blablubbabc** [comment]
A user of my plugin reported having this issue again. I suppose you reverted what I previously assumed might have fixed this in https://github.com/Auxilor/eco/commit/e9e39345edc9157d38fc9c521a868b6aa080ab80

Is there any way you can avoid modifying the result item involved in villager trades? Maybe an option could be to not actually modify the item on the server, but only the copy that is being sent to clients.

**Comment by Auxilor** [comment]
I only modify the object being sent to the client - however, I have to modify the NMS handle or the trade is cancelled altogether. It could be that the NMS handle is the server-side object? I could experiment with cancelling the OpenWindowMerchant packet and sending off a new one with modified recipes?

**Comment by blablubbabc** [comment]
It seems like the MerchantRecipes you get from ProtocolLib (https://github.com/Auxilor/eco/blob/8fbcf485b3dd7284072ef23cd25cf99cc053f19f/eco-core/core-plugin/src/main/java/com/willfp/eco/spigot/display/PacketOpenWindowMerchant.java#L29) are CraftMerchantRecipes, i.e. they are backed by the underlying Minecraft nms.MerchantRecipe of the original nms.MerchantRecipeList (via their 'handle').

> It could be that the NMS handle is the server-side object?

I think so, yes.

You then retrieve this underlying nms.MerchantRecipe via the handle and modify its result item ('sellingItem') (https://github.com/Auxilor/eco/blob/master/eco-core/core-nms/v1_16_R3/src/main/java/com/willfp/eco/proxy/v1_16_R3/VillagerTrade.java). This will modify the original nms.MerchantRecipes of the villager on the server.

(Offtopic: By the way, you also modify the result item of the bukkit MerchantRecipe portion of CraftMerchantRecipe ('result'). I don't think that this has any effect: That item is a copy, and changes to it are never applied to the underlying nms.MerchantRecipe or nms.ItemStack.)

Afterwards you then create a new MerchantRecipeList (https://github.com/Auxilor/eco/blob/8fbcf485b3dd7284072ef23cd25cf99cc053f19f/eco-core/core-plugin/src/main/java/com/willfp/eco/spigot/display/PacketOpenWindowMerchant.java#L33) of these modified MerchantRecipes. However, the original MerchantRecipes of the original MerchantRecipeList were already modified as well at that point.

> however, I have to modify the NMS handle or the trade is cancelled altogether.

Trades are usually cancelled if there is some mismatch between items in the slots and of the merchant recipe. However, without having looked into this deeper, I don't know whether the cancelling of the trade in your case happens on the client or the server (the mismatch of these items could be checked for on either side).
But since the server updates the item of the merchant result slot when the player inserts items or selects a trading recipe in the list, you may also have to intercept that slot update packet an modify the sent item there (for the client, not the server).

The goal would be to not modify any recipes or items on the server, but only the copies that are transferred to the client. So on the client, the recipe result item and result slot item would match your modified version, and on the server they would still be the originals (and match there as well).

> I could experiment with cancelling the OpenWindowMerchant packet and sending off a new one with modified recipes

I don't think this will resolve your trade cancelling issue if this is caused by the server modifying the result slot item to the non-modified server variant whenever something in the merchant inventory changes (input items, merchant recipe selection, etc.).

**Comment by Auxilor** [comment]
Fixed in eco 5.3.0 + ecoenchants 7.2.8

**Comment by blablubbabc** [comment]
Thanks! I tested this briefly and was not able to reproduce the compatibility issue between Eco and Shopkeepers anymore. And the previously affected items also no longer needlessly gain the additional 'finalized' tag on the client side either.

**Comment by blablubbabc** [comment]
I see you partially reverted your changes again in https://github.com/Auxilor/eco/commit/d65c04aaa75fe08bdcd116f5f75eb0f7dddbbef1 , modifying the original villager trades on the server (the handle) again.

May I ask what issue you ran into? If you ran into the "trade is cancelled altogether" issue you mentioned above: Your original change did not yet account for the slot items changing I mentioned above. So maybe try intercepting the relevant packet for that (https://wiki.vg/Protocol#Set_Slot) and modify the ItemStack being sent to clients to match the modified merchant recipe items.
