### ISSUE TITLE
transmission effect can teleport through/inside blocks

### ISSUE THREAD

**Issue by kamilleon** [Auxilor/eco#331]
**Describe the bug**

**To Reproduce**
1. Add transmission effect to an item, skill, anything
2. Find a wall, which has air blocks on the corners
3. Try to teleport from one side of the wall to the other (in the corner)
4. It teleports.

**Expected behavior**
It shouldn't teleport through.

**Server Information (please complete the following information):**
- Version: This server is running Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2)
- eco version 6.66.1, EcoItems version 5.33.0

**Comment by WillFP** [comment]
Not related to eco
