### ISSUE TITLE
circular plugin loading

### ISSUE THREAD

**Issue by Entrodor** [Auxilor/eco#337]
**Describe the bug**
server crashes due to circular plugin loading.
**To Reproduce**
use eco, executableitems, customcrafting, ecobosses/ecoitems/ecoarmor/ecoskills/ecoenchants together

**Expected behavior**
to not trigger paper's circular plugin loading crap

**Screenshots**
(log snippet small enough to not need screenshot.)
```
[SimpleProviderStorage]: eco -> ExecutableItems -> CustomCrafting -> EcoBosses -> eco
[SimpleProviderStorage]: eco -> ExecutableItems -> CustomCrafting -> EcoBosses -> EcoItems -> eco
[SimpleProviderStorage]: eco -> ExecutableItems -> CustomCrafting -> EcoSkills -> eco
[SimpleProviderStorage]: eco -> ExecutableItems -> CustomCrafting -> EcoArmor -> eco
[SimpleProviderStorage]: eco -> ExecutableItems -> CustomCrafting -> EcoEnchants -> eco
```

**Server Information (please complete the following information):**
- Server Version: git-Purpur-2062 (MC: 1.20.1)
- Eco: 6.67.0
- CustomCrafting version 4.16.8.5
- ExecutableItems version 6.23.12.5

**Additional context**
for now we tempfixed these issues by commenting out executableitems, customcrafting and itemsadder from eco's plugin.yml file

**Comment by WillFP** [comment]
Fixed
