### ISSUE TITLE
BUG!!!

### ISSUE THREAD

**Issue by TheFaik** [Auxilor/eco#350]
On Purpur 1.20.4-2155, because of the ECO library, it writes to the console which block the player broke. Please correct it. And the players began to complain that they could not mine ore.

**To Reproduce**
1. Download Purpur 1.20.4-2155
2. Download library ECO
3. Place the ECO plugin in the plugins folder.
4. On server

That there will be blocks in the console that the player has destroyed. Also sometimes players cannot mine ore.

**Screenshots**
Yes...

**Server Information (please complete the following information):**
- Version: git-Purpur-2155 (MC: 1.20.4)*
- Version of plugin and eco: eco version 6.69.0

**Comment by MrPibbly** [comment]
The console spam has been patched in today's update. The update should be available on all platforms now.
