### ISSUE TITLE
Conflict with FomalhautShop plugin

### ISSUE THREAD

**Issue by postyizhan** [Auxilor/eco#353]
**Describe the bug**
Conflict with FomalhautShop plugin

https://github.com/FxRayHughes/FomalhautShop

**To Reproduce**
-

**Expected behavior**
Enable two plugins to load properly

**Screenshots**
![f1c7158d3c05a0fefc82c4fb47036a14](https://github.com/Auxilor/eco/assets/97342038/25a4f010-e6bd-4429-80c0-cce1aa6478d4)

**Server Information (please complete the following information):**
- Version: -
- Version of plugin and eco -

**Additional context**
-

**Comment by TheFaik** [comment]
please update paper 1.20.6

**Comment by postyizhan** [comment]
> please update paper 1.20.6

Hello, thank you for your answer, but it has nothing to do with the paper version

**Comment by WillFP** [comment]
plugin conflict, ask  in discord so we can patch your fomalhautshop jar

**Comment by postyizhan** [comment]
> plugin conflict, ask in discord so we can patch your fomalhautshop jar

Hello, thank you for your reply (although it's a bit late). The author of the fomalhautshop plugin has fixed this issue
