### ISSUE TITLE
Error in Purpur 1.21 about SynchedEnityData.

### ISSUE THREAD

**Issue by TH2403y** [Auxilor/eco#362]
**Describe the bug**
For example, if I use the Ecomobs plugin to summon any monster, Ecomobs functions almost normally, except for the constant error

**To Reproduce**
1. Just Use Ecomobs to summon a mob

**Expected behavior**
The content in the image will appear

**Screenshots**

**Server Information (please complete the following information):**
- Version: 1.21 Purpur
- Version of plugin and eco: Eco 6.71.4 PAPI Protocolib spark  Ecomobs

![image](https://github.com/Auxilor/eco/assets/86739442/3b79bf38-10cb-4b29-8e9a-d5ce4d2f099b)
![image](https://github.com/Auxilor/eco/assets/86739442/c851324c-9f93-4842-b981-162cbdb95d80)
![image](https://github.com/Auxilor/eco/assets/86739442/0da9a82f-a42b-4af4-858d-646107dbb5ba)

**Comment by WillFP** [comment]
Fixed in latest! Thanks @lynxplay for the help with this one
