### ISSUE TITLE
NullPointerException of FastUtil

### ISSUE THREAD

**Issue by luizsusin** [Auxilor/eco#70]
Probably the FastItemStack is asynchronously handling ItemStacks that are being edited in the main-thread.
My players are being kicked for using Crates (which are looking awful, flickering a lot because of this) or for editing inventory too fast (both by using ChestSort or shift + click).

Disabling Eco's async-display makes everything go back to normal. Players aren't kicked anymore.

**Eco's Version:** 6.17.3
**StackTrace thrown:** https://pastebin.com/AAa3zSat

**Related Issues**
https://github.com/PaperMC/Paper/issues/7130
https://github.com/GeyserMC/Geyser/issues/2721
This one is mine, but:
https://github.com/PurpurMC/Purpur/issues/797

**Comment by AlternativeSoap** [comment]
I also got this error.

**Comment by WillFP** [comment]
Does this error still happen in 6.19.0?
