### ISSUE TITLE
Eco - Packet error

### ISSUE THREAD

**Issue by Aides123** [Auxilor/eco#81]
**Describe the bug**
The ECO plugin causes an error that throws players off the server.
During normal play, the player gets thrown by "Packet encoding of packet ID 20 threw (skippable? false)" and this occurs very frequently.
 Until now I didn't know the cause but on github protoclib I found (https://github.com/dmulloy2/ProtocolLib/issues/1495) and here the same error occurs. I have a large server (250 people) and several modes where this error does not occur, and on the mode where the error occurs from new plugins: ECO / REFORGES / SKILLS / ECOENCHANTS.

**To Reproduce**
I don't know what needs to be done for this to happen, the problem occurs during normal play when a player tries to create something, use an item.

**Expected behavior**
XXX

**Screenshots**
xxx

**Server Information (please complete the following information):**
- Version: This server is running Airplane version git-Airplane-"74774a0" (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 74774a0 on ver/1.17)
You are on the latest version!
Previous version: git-Pufferfish-20 (MC: 1.17.1)

- Version of plugin and eco (`/ver eco`, `/ver <plugin>`)
![image](https://user-images.githubusercontent.com/23367220/151406686-a9eee767-00b8-49f6-9bd0-71e0497c6d16.png)

**Additional context**
XXX

**Comment by WillFP** [comment]
Disable everything under async-display in `/plugins/eco/config.yml`
