### ISSUE TITLE
Suggestion: whitelist arg for drill and mine_radius effects

### ISSUE THREAD

**Issue by KermX** [Auxilor/eco#95]
These effects would be easier to configure if they use whitelist instead of a blacklist, I think generally people create these effects for a few specific blocks rather than everything with a few exceptions

Add a new arg to these effects, something like "use_as_whitelist: true/false" this solution would prevent people having to reconfigure their effects.

A separate whitelist arg or changing blacklist to whitelist would accomplish the same goal.

**Comment by WillFP** [comment]
Wrong repository, this should go in Auxilor/libreforge
